#  <span style="color:red">8/8</span>Exercise 09: Basic Numpy Operations

**Exercise 1:** Create a 3×3 numpy array of all True’s

In [25]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(A)
B = A<10
print(B)

A = np.full((3,3),True,dtype=bool)
print("3 x 3 numpy array of all True's:\n", A)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
3 x 3 numpy array of all True's:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Exercise 2:** Create a 1-D array of the numbers between 0 and 30. Create a new array from the first that only includes the odd values of your array.

In [30]:
import numpy as np
A1 = np.arange(1,30)
print('Array which includes values between 0 and 30:', A1)
B = A1[A1%2 != 0]
print('New array which includes only odd values from array A: ', B)

Array which includes values between 0 and 30: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
New array which includes only odd values from array A:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


**Exercise 3:** Using the first array from exercise 2, replace all odd numbers in the array with -1.

In [35]:
C = np.where(A1%2!=0,-1,A1)
print('Replaced all odd values with -1 in A1:\n', C)

Replaced all odd values with -1 in A1:
 [-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1 24
 -1 26 -1 28 -1]


**Exercise 4:** The function **np.reshape(A, (n, m))** takes in the array $A$ and converts it to an array of $n$ rows and $m$ columns. Write a function that creates a random 1D array of $n$ integers and converts in into a 2D array with 2 rows.

In [44]:
import numpy as numpy1
import random
def random_array(n):
    if n%2 != 0:
        n = n+1
    Arr = numpy1.arange(0,n)
    print('1D array of',  n, 'integers:\n', Arr)
    B_Arr = numpy1.reshape(Arr,(2,(n//2)))
    return B_Arr
print('Converted 1D array into 2D array with 2 rows:\n', random_array(random.randint(1,20)))

1D array of 10 integers:
 [0 1 2 3 4 5 6 7 8 9]
Converted 1D array into 2D array with 2 rows:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
